### ISSUE TITLE
adding Efficient V2 XL

### ISSUE THREAD

**Issue by mithils3** [sebastian-sz/efficientnet-v2-keras#11]

**Comment by sebastian-sz** [comment]
Hi,
thanks for the info. I didn't realize they released XL variant.
I did some quick prototyping yesterday and there are few issues. The XL model is so big that it:
* crashes the layer naming convention
* upon being created throws python `RecursionError` - my guess, due to the number of layers.

I will be trying to add it, but I do not have much time now, so it might take a while from my side. 

Thanks.

**Comment by mithils3** [comment]
You can take your time no problem

**Comment by sebastian-sz** [comment]
@king398 
Added in https://github.com/sebastian-sz/efficientnet-v2-keras/pull/12 .

You can reinstall repo and 
```python
from efficientnet_v2 import EfficientNetV2XL

```

**Comment by sebastian-sz** [comment]
I'm closing this as XL has been added. Feel free to repoen if you have questions.
